import { IMonsterEnvironments } from "../Context/Types";

export const forestMonsters = [
  "Animated Armor",
  "Brown Bear",
  "Bugbear",
] as string[];

export const barrens = [
  "Electrum Dragon",
  "Fang Dragon",
  "Wingless Wonder",
  "Dracohydra",
] as string[];

export const deserts = [
  "Abishai",
  "Abyssal Ghoul",
  "Adamantine Golem",
  "Advespa",
  "Amnizu",
  "Arcane",
  "Baelnorn",
  "Bariaur",
  "Battleloth",
  "Behir",
  "Belker",
  "Blooded One",
  "Bloodthorn",
  "Boggle",
  "Bonebat",
  "Braxat",
  "Brown Dragon",
  "Burnbones",
  "Cockatrice",
  "Corpse Tearer",
  "Crested Felldrake",
  "Dao",
  "Decation",
  "Deep Bat",
  "Desert Cyclops",
  "Deva",
  "Dire Horse",
  "Dracolisk",
  "Dead Linnorm",
  "Dread Wolf",
  "Duodrone",
  "Eatern Vampire",
  "Feng Huang",
  "Firre",
  "Foo Creature",
  "Foo Dog",
  "Foo Lion",
  "Force Dragon",
  "Fossergrim",
  "Fremlin",
  "Frost Salamander",
  "Galltrit",
  "Ghargatula",
  "Ghost rothe",
  "Ghour",
  "Goristro",
  "Hellfire Wyrm",
  "Hexton",
  "Ibrandin",
  "Ice Drake",
  "Kelpie",
  "Kir-Ianan",
  "Kocrachon",
  "Landwyrm",
  "Lightning Golem",
  "Lunar Ravager",
  "Malaugrym",
  "Marid",
  "megalo-Centipede",
  "Modron",
  "Mummy",
  "Myrlochar",
  "Necrophidius",
  "Night Hunter",
  "Nilshai",
  "Nonaton",
  "Nyth",
  "Ogrima",
  "Ondonti",
  "Ormyrr",
  "Penanggalan",
  "Pentadrone",
  "Petitioner",
  "Phane",
  "Phoenix",
  "Pink Dragon",
  "Prismatic Dragon",
  "Quadrone",
  "Remorhaz",
  "Revenant",
  "Secundus",
  "Sahde",
  "Shedu",
  "Shirokinkatsukami",
  "Silat",
  "Silveraith",
  "Skeroloth",
  "Song Dragon",
  "Spawn of Kyuss",
  "Specter",
  "Spectral Panther",
  "Spinagon",
  "Sword Wraith",
  "Talisman Servant",
  "Tanarukk",
  "Tertian",
  "Thornslinger",
  "Giant Troll",
  "Tyrantfog Zombie",
  "Urdezu",
  "Vampiric Wolf",
  "Varrangoin",
  "Vorr",
  "Watchghost",
  "Water Weird",
  "Wingless Wonder",
  "Wood Element Creature",
  "Wraithworm",
  "Xill",
  "Yellow MAsk Creeper",
  "Yeth Hound",
  "Yochlol",
  "Zakharan Ogre",
  "Zin-carla",
  "Juju Zombie",
] as string[];

export const dungeonsAndRuins = [
  "Crypt Thing",
  "Greelox",
  "Ruin Chanter",
  "Ruin Elemental",
  "Wingless Wonder",
  "Vamire Bat",
  "Lamia",
  "Ear Seeker",
  "Darktentacles",
  "Nasnas",
  "Serpent Lord",
  "Topi",
] as string[];

export const lakes = [
  "Amethyst Dragon",
  "Bloodbloater",
  "Flotsam Ooze",
  "Giant Frog",
  "Hetfish",
  "Killer Frog",
  "Lacedon",
  "Piranha",
  "Reekmurk",
  "Rusalka",
  "Aquatic Elf",
  "Asrai",
  "Bunyip",
  "Kappa",
  "Giant Pike",
  "Merrow",
  "Quelzarn",
  "Shen Lung",
  "Sirine",
  "Skuz",
  "Throat Leech",
  "Toad",
  "Electric Eel",
  "Zaraton",
  "Giant Carp",
  "Behemoth",
  "Reekmurk",
] as string[];

export const monsterRegions = [
  "All",
  "Cities",
  "Caves",
  "Ruines",
  "Plains",
  "Mountains",
  "Deserts",
  "Swamps",
  "Lakes",
  "Rivers",
  "Oceans",
];

export const allMonstersEnv = [
  {
    name: "Aboleth",
    environments: ["All", "Lakes", "Ruines", "Oceans", "Caves"],
  },
  {
    name: "Acolyte",
    environments: [
      "All",
      "Cities",
      "Ruines",
      "Plains",
      "Mountains",
      "Deserts",
      "Swamps",
      "Caves",
      "Volcanoes",
    ],
  },
  {
    name: "Adult Black Dragon",
    environments: ["All", "Swamps", "Forests", "Caves"],
  },
  {
    name: "Adult Blue Dragon",
    environments: ["All", "Caves", "Deserts", "Caves"],
  },
  {
    name: "Adult Brass Dragon",
    environments: ["All", "Ruines", "Caves", "Deserts"],
  },
  { name: "Adult Bronze Dragon", environments: ["All", "Oceans", "Caves"] },
  {
    name: "Adult Copper Dragon",
    environments: ["All", "Mountains", "Deserts", " Plains"],
  },
  {
    name: "Adult Gold Dragon",
    environments: ["All", "Lakes", "Rivers", "Ruines", "Caves"],
  },
  {
    name: "Adult Green Dragon",
    environments: ["All", "Plains", "Forests", "Caves"],
  },
  {
    name: "Adult Red Dragon",
    environments: ["All", "Plains", "Mountains", "Cave"],
  },
  { name: "Adult Silver Dragon", environments: ["All", "Mountains", "Caves"] },
  {
    name: "Adult White Dragon",
    environments: ["All", "Mountains", "Caves", "Snow"],
  },
  { name: "Air Elemental", environments: ["All", "Plains", "Mountains"] },
  {
    name: "Ancient Black Dragon",
    environments: ["All", "Swamps", "Forests", "Caves"],
  },
  {
    name: "Ancient Blue Dragon",
    environments: ["All", "Caves", "Deserts", "Caves"],
  },
  {
    name: "Ancient Brass Dragon",
    environments: ["All", "Ruines", "Caves", "Deserts"],
  },
  { name: "Ancient Bronze Dragon", environments: ["All", "Oceans", "Caves"] },
  {
    name: "Ancient Copper Dragon",
    environments: ["All", "Mountains", "Deserts", " Plains"],
  },
  {
    name: "Ancient Gold Dragon",
    environments: ["All", "Lakes", "Rivers", "Ruines", "Caves"],
  },
  {
    name: "Ancient Green Dragon",
    environments: ["All", "Plains", "Forests", "Caves"],
  },
  {
    name: "Ancient Red Dragon",
    environments: ["All", "Plains", "Mountains", "Cave"],
  },
  {
    name: "Ancient Silver Dragon",
    environments: ["All", "Mountains", "Caves"],
  },
  {
    name: "Ancient White Dragon",
    environments: ["All", "Mountains", "Caves", "Snow"],
  },
  {
    name: "Androsphinx",
    environments: ["All", "Mountains", "Plains", "Desert"],
  },
  {
    name: "Animated Armor",
    environments: ["All", "Cities", "Ruines", "Caves", "Swamps"],
  },
  { name: "Ankheg", environments: ["All", "Deserts", "Caves"] },
  { name: "Ape", environments: ["All", "Forrests"] },
  { name: "Archmage", environments: ["All", "Cities", "Ruines", "Swamps"] },
  { name: "Assassin", environments: ["All", "Cities", "Ruins", "Swamps"] },
  { name: "Awakened Shrub", environments: ["All", "Forrests"] },
  { name: "Awakened Tree", environments: ["All", "Forrests"] },
  { name: "Axe Beak", environments: ["All", "Forrests"] },
  { name: "Azer", environments: ["All", "Volcanoes", "Hell"] },
  { name: "Baboon", environments: ["All", "Forrests"] },
  { name: "Badger", environments: ["All", "Forrests", "Plains"] },
  { name: "Balor", environments: ["All", "Volcanoes", "Caves", "Hell"] },
  { name: "Bandit", environments: ["All", "Cities", "Ruines", "Caves"] },
  {
    name: "Bandit Captain",
    environments: ["All", "Cities", "Ruines", "Caves"],
  },
  { name: "Barbed Devil", environments: ["All", "Volcanoes", "Hell"] },
  { name: "Basilisk", environments: ["All", "Volcanoes", "Desert"] },
  {
    name: "Bat",
    environments: ["All", "Caves", "Forrests", "Deserts", "Swamps"],
  },
  { name: "Bearded Devil", environments: ["All", "Deserts"] },
  { name: "Behir", environments: ["All", "Caves", "Volcanoes", "Plains"] },
  { name: "Berserker", environments: ["All", "Plains", "Deserts"] },
  { name: "Black Bear", environments: ["All", "Forrests", "Mountains"] },
  {
    name: "Black Dragon Wyrmling",
    environments: ["All", "Swamps", "Forests", "Caves"],
  },
  { name: "Black Pudding", environments: ["All", "Swamps"] },
  { name: "Blink Dog", environments: ["All", "Hell", "Volcanoes", "Swamps"] },
  { name: "Blood Hawk", environments: ["All", "Forrests"] },
  {
    name: "Blue Dragon Wyrmling",
    environments: ["All", "Caves", "Deserts", "Caves"],
  },
  { name: "Boar", environments: ["All", "Forrests"] },
  { name: "Bone Devil", environments: ["All", "Hell", "Volcanoes"] },
  {
    name: "Brass Dragon Wyrmling",
    environments: ["All", "Ruines", "Caves", "Deserts"],
  },
  { name: "Bronze Dragon Wyrmling", environments: ["All", "Oceans", "Caves"] },
  {
    name: "Brown Bear",
    environments: ["All", "Forrests", "Caves", "Mountains"],
  },
  { name: "Bugbear", environments: ["All", "Forrests", "Caves"] },
  { name: "Bulette", environments: ["All", "Caves"] },
  { name: "Camel", environments: ["All", "Mountains"] },
  { name: "Cat", environments: ["All", "Cities", "Forrests"] },
  { name: "Centaur", environments: ["All", "Forrests", "Plains"] },
  { name: "Chain Devil", environments: ["All", "Hell", "Volcanoes"] },
  {
    name: "Chimera",
    environments: ["All", "Volcanoes", "Caves", "Plains", "Mountains"],
  },
  { name: "Chuul", environments: ["All", "Ocean"] },
  { name: "Clay Golem", environments: ["All", "Caves", "Mountains"] },
  { name: "Cloaker", environments: ["All", "Caves"] },
  { name: "Cloud Giant", environments: ["All", "Mountains"] },
  { name: "Cockatrice", environments: ["All", "Mountains", "Caves"] },
  { name: "Commoner", environments: ["All", "Cities", "Ruines", "Plains"] },
  { name: "Constrictor Snake", environments: ["All", "Forrests"] },
  {
    name: "Copper Dragon Wyrmling",
    environments: ["All", "Mountains", "Deserts", " Plains"],
  },
  { name: "Couatl", environments: ["All", "Forrests"] },
  { name: "Crab", environments: ["All", "Oceans", "Lakes"] },
  {
    name: "Crocodile",
    environments: ["All", "Oceans", "Lakes", "Rivers", "Swamps"],
  },
  {
    name: "Cult Fanatic",
    environments: ["All", "Swamps", "Ruines", "Cities", "Caves"],
  },
  {
    name: "Cultist",
    environments: ["All", "Swamps", "Ruines", "Cities", "Caves"],
  },
  { name: "Darkmantle", environments: ["All", "Oceans"] },
  { name: "Death Dog", environments: ["All", "Hell", "Volanoes"] },
  {
    name: "Deep Gnome (Svirfneblin)",
    environments: ["All", "Caves", "Ruines"],
  },
  { name: "Deer", environments: ["All", "Forrests"] },
  { name: "Deva", environments: ["All", "Mountains"] },
  { name: "Dire Wolf", environments: ["All", "Forrests", "Mountains"] },
  { name: "Djinni", environments: ["All", "Mountains", "Ruines"] },
  { name: "Doppelganger", environments: ["All", "Ruines", "Caves", "Cities"] },
  { name: "Draft Horse", environments: ["All", "Cities", "Forrests"] },
  { name: "Dragon Turtle", environments: ["All", "Oceans", "Lakes"] },
  { name: "Dretch", environments: ["All", "Hell"] },
  { name: "Drider", environments: ["All", "Forrests", "Caves"] },
  { name: "Drow", environments: ["All", "Forrests", "Riveres"] },
  { name: "Druid", environments: ["All", "Forrests", "Riveres"] },
  { name: "Dryad", environments: ["All", "Forrests", "Rivers"] },
  { name: "Duergar", environments: ["All", "Caves", "Cities", "Mountains"] },
  { name: "Dust Mephit", environments: ["All", "Hell"] },
  { name: "Eagle", environments: ["All", "Mountains"] },
  { name: "Earth Elemental", environments: ["All", "Mountains", "Caves"] },
  { name: "Efreeti", environments: ["All", "Hell", "Volcanoes"] },
  { name: "Elephant", environments: ["All", "Deserts"] },
  { name: "Elk", environments: ["All", "Forrests"] },
  { name: "Erinyes", environments: ["All", "Mountains", "Hell", "Volcanoes"] },
  { name: "Ettercap", environments: ["All", "Swamps", "Hell"] },
  { name: "Ettin", environments: ["All", "Caves", "Plains", "Forrests"] },
  {
    name: "Fire Elemental",
    environments: ["All", "Volcanoes", "Hell", "Deserts"],
  },
  {
    name: "Fire Giant",
    environments: [
      "All",
      "Volcanoes",
      "Deserts",
      "Plains",
      "Mountains",
      "Caves",
    ],
  },
  {
    name: "Flesh Golem",
    environments: ["All", "Caves", "Mountains", "Swamps"],
  },
  {
    name: "Flying Snake",
    environments: ["All", "Deserts", "Caves", "Forrests", "Swamps", "Ruines"],
  },
  { name: "Flying Sword", environments: ["All", "Caves", "Ruines", "Cities"] },
  {
    name: "Frog",
    environments: ["All", "Swamps", "Rivers", "Lakes", "Forrests"],
  },
  { name: "Frost Giant", environments: ["All", "Snow", "Mountains", "Caves"] },
  { name: "Gargoyle", environments: ["All", "Mountains", "Caves"] },
  {
    name: "Gelatinous Cube",
    environments: ["All", "Ruines", "Caves", "Swamp"],
  },
  { name: "Ghast", environments: ["All", "Swamp", "Caves", "Hell"] },
  { name: "Ghost", environments: ["All", "Swamp", "Caves", "Hell", "Cities"] },
  { name: "Ghoul", environments: ["All", "Caves", "Swamps", "Hell"] },
  { name: "Giant Ape", environments: ["All", "Forrests"] },
  { name: "Giant Badger", environments: ["All", "Forrests", "Plains"] },
  { name: "Giant Bat", environments: ["All", "Caves", "Forrests"] },
  { name: "Giant Boar", environments: ["All", "Forrests", "Plains"] },
  { name: "Giant Centipede", environments: ["All", "Caves", "Hell"] },
  {
    name: "Giant Constrictor Snake",
    environments: ["All", "Corrests", "Caves", "Rivers"],
  },
  { name: "Giant Crab", environments: ["All", "Rivers", "Lakes", "Oceans"] },
  {
    name: "Giant Crocodile",
    environments: ["All", "Rivers", "Lakes", "Oceans"],
  },
  { name: "Giant Eagle", environments: ["All"] },
  { name: "Giant Elk", environments: ["All"] },
  { name: "Giant Fire Beetle", environments: ["All"] },
  { name: "Giant Frog", environments: ["All"] },
  { name: "Giant Goat", environments: ["All"] },
  { name: "Giant Hyena", environments: ["All"] },
  { name: "Giant Lizard", environments: ["All"] },
  { name: "Giant Octopus", environments: ["All"] },
  { name: "Giant Owl", environments: ["All"] },
  { name: "Giant Poisonous Snake", environments: ["All"] },
  { name: "Giant Rat", environments: ["All"] },
  { name: "Giant Rat (Diseased)", environments: ["All"] },
  { name: "Giant Scorpion", environments: ["All"] },
  { name: "Giant Sea Horse", environments: ["All"] },
  { name: "Giant Shark", environments: ["All"] },
  { name: "Giant Spider", environments: ["All"] },
  { name: "Giant Toad", environments: ["All"] },
  { name: "Giant Vulture", environments: ["All"] },
  { name: "Giant Wasp", environments: ["All"] },
  { name: "Giant Weasel", environments: ["All"] },
  { name: "Giant Wolf Spider", environments: ["All"] },
  { name: "Gibbering Mouther", environments: ["All"] },
  { name: "Glabrezu", environments: ["All"] },
  { name: "Gladiator", environments: ["All"] },
  { name: "Gnoll", environments: ["All"] },
  { name: "Goat", environments: ["All"] },
  { name: "Goblin", environments: ["All"] },
  {
    name: "Gold Dragon Wyrmling",
    environments: ["All", "Lakes", "Rivers", "Ruines", "Caves"],
  },
  { name: "Gorgon", environments: ["All"] },
  { name: "Gray Ooze", environments: ["All"] },
  {
    name: "Green Dragon Wyrmling",
    environments: ["All", "Plains", "Forests", "Caves"],
  },
  { name: "Green Hag", environments: ["All"] },
  { name: "Grick", environments: ["All"] },
  { name: "Griffon", environments: ["All"] },
  { name: "Grimlock", environments: ["All"] },
  { name: "Guard", environments: ["All"] },
  { name: "Guardian Naga", environments: ["All"] },
  { name: "Gynosphinx", environments: ["All"] },
  { name: "Half-Red Dragon Veteran", environments: ["All"] },
  { name: "Harpy", environments: ["All"] },
  { name: "Hawk", environments: ["All"] },
  { name: "Hell Hound", environments: ["All"] },
  { name: "Hezrou", environments: ["All"] },
  { name: "Hill Giant", environments: ["All"] },
  { name: "Hippogriff", environments: ["All"] },
  { name: "Hobgoblin", environments: ["All"] },
  { name: "Homunculus", environments: ["All"] },
  { name: "Horned Devil", environments: ["All"] },
  { name: "Hunter Shark", environments: ["All"] },
  { name: "Hydra", environments: ["All"] },
  { name: "Hyena", environments: ["All"] },
  { name: "Ice Devil", environments: ["All"] },
  { name: "Ice Mephit", environments: ["All"] },
  { name: "Imp", environments: ["All"] },
  { name: "Invisible Stalker", environments: ["All"] },
  { name: "Iron Golem", environments: ["All"] },
  { name: "Jackal", environments: ["All"] },
  { name: "Killer Whale", environments: ["All"] },
  { name: "Knight", environments: ["All"] },
  { name: "Kobold", environments: ["All"] },
  { name: "Kraken", environments: ["All"] },
  { name: "Lamia", environments: ["All"] },
  { name: "Lemure", environments: ["All"] },
  { name: "Lich", environments: ["All"] },
  { name: "Lion", environments: ["All"] },
  { name: "Lizard", environments: ["All"] },
  { name: "Lizardfolk", environments: ["All"] },
  { name: "Mage", environments: ["All"] },
  { name: "Magma Mephit", environments: ["All"] },
  { name: "Magmin", environments: ["All"] },
  { name: "Mammoth", environments: ["All"] },
  { name: "Manticore", environments: ["All"] },
  { name: "Marilith", environments: ["All"] },
  { name: "Mastiff", environments: ["All"] },
  { name: "Medusa", environments: ["All"] },
  { name: "Merfolk", environments: ["All"] },
  { name: "Merrow", environments: ["All"] },
  { name: "Mimic", environments: ["All"] },
  { name: "Minotaur", environments: ["All"] },
  { name: "Minotaur Skeleton", environments: ["All"] },
  { name: "Mule", environments: ["All"] },
  { name: "Mummy", environments: ["All"] },
  { name: "Mummy Lord", environments: ["All"] },
  { name: "Nalfeshnee", environments: ["All"] },
  { name: "Night Hag", environments: ["All"] },
  { name: "Nightmare", environments: ["All"] },
  { name: "Noble", environments: ["All"] },
  { name: "Ochre Jelly", environments: ["All"] },
  { name: "Octopus", environments: ["All"] },
  { name: "Ogre", environments: ["All"] },
  { name: "Ogre Zombie", environments: ["All"] },
  { name: "Oni", environments: ["All"] },
  { name: "Orc", environments: ["All"] },
  { name: "Otyugh", environments: ["All"] },
  { name: "Owl", environments: ["All"] },
  { name: "Owlbear", environments: ["All"] },
  { name: "Panther", environments: ["All"] },
  { name: "Pegasus", environments: ["All"] },
  { name: "Phase Spider", environments: ["All"] },
  { name: "Pit Fiend", environments: ["All"] },
  { name: "Planetar", environments: ["All"] },
  { name: "Plesiosaurus", environments: ["All"] },
  { name: "Poisonous Snake", environments: ["All"] },
  { name: "Polar Bear", environments: ["All"] },
  { name: "Pony", environments: ["All"] },
  { name: "Priest", environments: ["All"] },
  { name: "Pseudodragon", environments: ["All"] },
  { name: "Purple Worm", environments: ["All"] },
  { name: "Quasit", environments: ["All"] },
  { name: "Quipper", environments: ["All"] },
  { name: "Rakshasa", environments: ["All"] },
  { name: "Rat", environments: ["All"] },
  { name: "Raven", environments: ["All"] },
  {
    name: "Red Dragon Wyrmling",
    environments: ["All", "Plains", "Mountains", "Cave"],
  },
  { name: "Reef Shark", environments: ["All"] },
  { name: "Remorhaz", environments: ["All"] },
  { name: "Rhinoceros", environments: ["All"] },
  { name: "Riding Horse", environments: ["All"] },
  { name: "Roc", environments: ["All"] },
  { name: "Roper", environments: ["All"] },
  { name: "Rug of Smothering", environments: ["All"] },
  { name: "Rust Monster", environments: ["All"] },
  { name: "Saber-Toothed Tiger", environments: ["All"] },
  { name: "Sahuagin", environments: ["All"] },
  { name: "Salamander", environments: ["All"] },
  { name: "Satyr", environments: ["All"] },
  { name: "Scorpion", environments: ["All"] },
  { name: "Scout", environments: ["All"] },
  { name: "Sea Hag", environments: ["All"] },
  { name: "Sea Horse", environments: ["All"] },
  { name: "Shadow", environments: ["All"] },
  { name: "Shambling Mound", environments: ["All"] },
  { name: "Shield Guardian", environments: ["All"] },
  { name: "Shrieker", environments: ["All"] },
  {
    name: "Silver Dragon Wyrmling",
    environments: ["All", "Mountains", "Caves"],
  },
  { name: "Skeleton", environments: ["All"] },
  { name: "Solar", environments: ["All"] },
  { name: "Specter", environments: ["All"] },
  { name: "Spider", environments: ["All"] },
  { name: "Spirit Naga", environments: ["All"] },
  { name: "Sprite", environments: ["All"] },
  { name: "Spy", environments: ["All"] },
  { name: "Steam Mephit", environments: ["All"] },
  { name: "Stirge", environments: ["All"] },
  { name: "Stone Giant", environments: ["All"] },
  { name: "Stone Golem", environments: ["All"] },
  { name: "Storm Giant", environments: ["All"] },
  { name: "Succubus/Incubus", environments: ["All"] },
  { name: "Swarm of Bats", environments: ["All"] },
  { name: "Swarm of Beetles", environments: ["All"] },
  { name: "Swarm of Centipedes", environments: ["All"] },
  { name: "Swarm of Insects", environments: ["All"] },
  { name: "Swarm of Poisonous Snakes", environments: ["All"] },
  { name: "Swarm of Quippers", environments: ["All"] },
  { name: "Swarm of Rats", environments: ["All"] },
  { name: "Swarm of Ravens", environments: ["All"] },
  { name: "Swarm of Spiders", environments: ["All"] },
  { name: "Swarm of Wasps", environments: ["All"] },
  { name: "Tarrasque", environments: ["All"] },
  { name: "Thug", environments: ["All"] },
  { name: "Tiger", environments: ["All"] },
  { name: "Treant", environments: ["All"] },
  { name: "Tribal Warrior", environments: ["All"] },
  { name: "Triceratops", environments: ["All"] },
  { name: "Troll", environments: ["All"] },
  { name: "Tyrannosaurus Rex", environments: ["All"] },
  { name: "Unicorn", environments: ["All"] },
  { name: "Vampire, Bat Form", environments: ["All"] },
  { name: "Vampire, Mist Form", environments: ["All"] },
  { name: "Vampire Spawn", environments: ["All"] },
  { name: "Vampire, Vampire Form", environments: ["All"] },
  { name: "Veteran", environments: ["All"] },
  { name: "Violet Fungus", environments: ["All"] },
  { name: "Vrock", environments: ["All"] },
  { name: "Vulture", environments: ["All"] },
  { name: "Warhorse", environments: ["All"] },
  { name: "Warhorse Skeleton", environments: ["All"] },
  { name: "Water Elemental", environments: ["All"] },
  { name: "Weasel", environments: ["All"] },
  { name: "Werebear, Bear Form", environments: ["All"] },
  { name: "Werebear, Human Form", environments: ["All"] },
  { name: "Werebear, Hybrid Form", environments: ["All"] },
  { name: "Wereboar, Boar Form", environments: ["All"] },
  { name: "Wereboar, Human Form", environments: ["All"] },
  { name: "Wereboar, Hybrid Form", environments: ["All"] },
  { name: "Wererat, Human Form", environments: ["All"] },
  { name: "Wererat, Hybrid Form", environments: ["All"] },
  { name: "Wererat, Rat Form", environments: ["All"] },
  { name: "Weretiger, Human Form", environments: ["All"] },
  { name: "Weretiger, Hybrid Form", environments: ["All"] },
  { name: "Weretiger, Tiger Form", environments: ["All"] },
  { name: "Werewolf, Human Form", environments: ["All"] },
  { name: "Werewolf, Hybrid Form", environments: ["All"] },
  { name: "Werewolf, Wolf Form", environments: ["All"] },
  {
    name: "White Dragon Wyrmling",
    environments: ["All", "Mountains", "Caves", "Snow"],
  },
  { name: "Wight", environments: ["All"] },
  { name: "Will-o'-Wisp", environments: ["All"] },
  { name: "Winter Wolf", environments: ["All"] },
  { name: "Wolf", environments: ["All"] },
  { name: "Worg", environments: ["All"] },
  { name: "Wraith", environments: ["All"] },
  { name: "Wyvern", environments: ["All"] },
  { name: "Xorn", environments: ["All"] },
  {
    name: "Young Black Dragon",
    environments: ["All", "Swamps", "Forests", "Caves"],
  },
  {
    name: "Young Blue Dragon",
    environments: ["All", "Caves", "Deserts", "Caves"],
  },
  {
    name: "Young Brass Dragon",
    environments: ["All", "Ruines", "Caves", "Deserts"],
  },
  { name: "Young Bronze Dragon", environments: ["All", "Oceans", "Caves"] },
  {
    name: "Young Copper Dragon",
    environments: ["All", "Mountains", "Deserts", " Plains"],
  },
  {
    name: "Young Gold Dragon",
    environments: ["All", "Lakes", "Rivers", "Ruines", "Caves"],
  },
  {
    name: "Young Green Dragon",
    environments: ["All", "Plains", "Forests", "Caves"],
  },
  {
    name: "Young Red Dragon",
    environments: ["All", "Plains", "Mountains", "Cave"],
  },
  { name: "Young Silver Dragon", environments: ["All", "Mountains", "Caves"] },
  {
    name: "Young White Dragon",
    environments: ["All", "Mountains", "Caves", "Snow"],
  },
  { name: "Zombie", environments: ["All"] },
] as IMonsterEnvironments[];
